[env:m5stack-cardputer]
platform = espressif32
; O Cardputer usa o modulo M5Stack StampS3.
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5Cardputer
  m5stack/M5Unified
  m5stack/M5GFX
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -I.
